{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shoreguard.secretName" . }}
  labels:
    {{- include "shoreguard.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.admin.password | b64enc | quote }}
  secret-key: {{ include "shoreguard.secretKeyValue" . | b64enc | quote }}
{{- end }}
