"""Machine-readable error codes for API responses."""

from __future__ import annotations

GATEWAY_NOT_CONNECTED = "GATEWAY_NOT_CONNECTED"
NOT_FOUND = "NOT_FOUND"
POLICY_ERROR = "POLICY_ERROR"
SANDBOX_CONFLICT = "SANDBOX_CONFLICT"
VALIDATION_ERROR = "VALIDATION_ERROR"
TIMEOUT = "TIMEOUT"
RATE_LIMITED = "RATE_LIMITED"
AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
PERMISSION_DENIED = "PERMISSION_DENIED"
CONFLICT = "CONFLICT"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
INTERNAL_ERROR = "INTERNAL_ERROR"

_STATUS_CODE_FALLBACK: dict[int, str] = {
    400: VALIDATION_ERROR,
    422: VALIDATION_ERROR,
    401: AUTHENTICATION_REQUIRED,
    403: PERMISSION_DENIED,
    404: NOT_FOUND,
    409: CONFLICT,
    429: RATE_LIMITED,
    500: INTERNAL_ERROR,
    503: SERVICE_UNAVAILABLE,
    504: TIMEOUT,
}


def code_for_status(status: int) -> str:
    """Return a default error code for an HTTP status.

    Args:
        status: The HTTP status code.

    Returns:
        str: The corresponding error code constant.
    """
    return _STATUS_CODE_FALLBACK.get(status, INTERNAL_ERROR)
